(newline)
(display "pleas enter three numbers:")
(newline)
(define a (read))
(define b (read))
(define c (read))
(define t (if (> a b) a b))
(define sum (if (= a b) (if (> a c) (+ a b) (+ a c)) (+ t (cond ((= t a) (if (> b c) b c)) ((= t b) (if (> a c) a c))))))
(display "The sum of two largest number is ")
(display sum)
